public class CaseConstants {
   
    public static final String CASE_STATUS_CLOSED ='Closed';
    public static final String TEST_EMAIL = 'test@gmail.com';
    public static final String NEW_STATUS = 'New';
    public static final String CLOSED_STATUS = 'Closed';
    public static final String SUBJECT ='Subject';
    public static final String REASON = 'Reason';
    public static final String SUPPLIED_EMAIL = 'Supplied Email'; 
}
