public class CaseSolutionTriggerConstants {

    public static final String RESOLVED_VIA_CALL = 'Resolved via call';
    public static final String RESOLVED_IN_ADVANCE = 'Resolved in advance';
    public static final String CANCELLED = 'Cancelled';
    public static final String RESOLVED = 'Resolved';
    public static final String NEW_STATUS = 'New';
    public static final String CALL = 'Call';
    public static final String EMAIL = 'Email';
    public static final String CONSULTATION = 'Consultation';
    public static final String NEED_A_CHECK = 'Need a check';
    public static final String NO_ANSWER = 'No answer';
}
