public class UpdateLeadBatchConstants {

    public static final String SYSTEM_ADMINISTRATOR = 'System Administrator';
    public static final String OPEN_STATUS ='Open%';
    public static final String CRON_EXP = '0 0 0/1 1/1 * ? *';
    public static final String OPEN_NOT_CONTACTED ='Open - not Contacted';
    public static final String SCHEDULE_NAME ='ScheduledApexTest';
    public static final String CLOSED_CONVERTED = 'Closed - Converted';
    public static final String TEST_LAST_NAME = 'Test last name ';
    public static final String TEST_COMPANY = 'Test company ';
    public static final String BUDGET_CONFIRMED_AMOUNT_KNOWN = 'Budget Confirmed, Amount Known';
    public static final String ACCESS_TO_BUYER_CONFIRMED = 'Access to Buyer Confirmed';
}
